//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BebelBaby.API.wcfGeradorLigacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pcservice.com.br/controlpc", ConfigurationName="wcfGeradorLigacao.WSControlPCSoap")]
    public interface WSControlPCSoap {
        
        // CODEGEN: Generating message contract since message GerarLigacaoMCareRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pcservice.com.br/controlpc/GerarLigacaoMCare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse GerarLigacaoMCare(BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pcservice.com.br/controlpc/GerarLigacaoMCare", ReplyAction="*")]
        System.Threading.Tasks.Task<BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse> GerarLigacaoMCareAsync(BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pcservice.com.br/controlpc")]
    public partial class PersonalAuthentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigo_AsteriskField;
        
        private string usuarioField;
        
        private string senhaField;
        
        private string login_RedeField;
        
        private string aplicacao_NomeField;
        
        private string aplicacao_VersaoField;
        
        private string hostNameField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Codigo_Asterisk {
            get {
                return this.codigo_AsteriskField;
            }
            set {
                this.codigo_AsteriskField = value;
                this.RaisePropertyChanged("Codigo_Asterisk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Login_Rede {
            get {
                return this.login_RedeField;
            }
            set {
                this.login_RedeField = value;
                this.RaisePropertyChanged("Login_Rede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Aplicacao_Nome {
            get {
                return this.aplicacao_NomeField;
            }
            set {
                this.aplicacao_NomeField = value;
                this.RaisePropertyChanged("Aplicacao_Nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Aplicacao_Versao {
            get {
                return this.aplicacao_VersaoField;
            }
            set {
                this.aplicacao_VersaoField = value;
                this.RaisePropertyChanged("Aplicacao_Versao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string HostName {
            get {
                return this.hostNameField;
            }
            set {
                this.hostNameField = value;
                this.RaisePropertyChanged("HostName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pcservice.com.br/controlpc")]
    public partial class MedicaoMCare : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dDI_Telefone_MedicoField;
        
        private string dDD_Telefone_MedicoField;
        
        private string telefone_MedicoField;
        
        private string dDI_Telefone_PacienteField;
        
        private string dDD_Telefone_PacienteField;
        
        private string telefone_PacienteField;
        
        private string nome_PacienteField;
        
        private System.DateTime data_MedicaoField;
        
        private Tipo_Medicao tipo_MedicaoField;
        
        private float val1Field;
        
        private float val2Field;
        
        private float val3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DDI_Telefone_Medico {
            get {
                return this.dDI_Telefone_MedicoField;
            }
            set {
                this.dDI_Telefone_MedicoField = value;
                this.RaisePropertyChanged("DDI_Telefone_Medico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DDD_Telefone_Medico {
            get {
                return this.dDD_Telefone_MedicoField;
            }
            set {
                this.dDD_Telefone_MedicoField = value;
                this.RaisePropertyChanged("DDD_Telefone_Medico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Telefone_Medico {
            get {
                return this.telefone_MedicoField;
            }
            set {
                this.telefone_MedicoField = value;
                this.RaisePropertyChanged("Telefone_Medico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DDI_Telefone_Paciente {
            get {
                return this.dDI_Telefone_PacienteField;
            }
            set {
                this.dDI_Telefone_PacienteField = value;
                this.RaisePropertyChanged("DDI_Telefone_Paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DDD_Telefone_Paciente {
            get {
                return this.dDD_Telefone_PacienteField;
            }
            set {
                this.dDD_Telefone_PacienteField = value;
                this.RaisePropertyChanged("DDD_Telefone_Paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Telefone_Paciente {
            get {
                return this.telefone_PacienteField;
            }
            set {
                this.telefone_PacienteField = value;
                this.RaisePropertyChanged("Telefone_Paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Nome_Paciente {
            get {
                return this.nome_PacienteField;
            }
            set {
                this.nome_PacienteField = value;
                this.RaisePropertyChanged("Nome_Paciente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime Data_Medicao {
            get {
                return this.data_MedicaoField;
            }
            set {
                this.data_MedicaoField = value;
                this.RaisePropertyChanged("Data_Medicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Tipo_Medicao Tipo_Medicao {
            get {
                return this.tipo_MedicaoField;
            }
            set {
                this.tipo_MedicaoField = value;
                this.RaisePropertyChanged("Tipo_Medicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public float Val1 {
            get {
                return this.val1Field;
            }
            set {
                this.val1Field = value;
                this.RaisePropertyChanged("Val1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public float Val2 {
            get {
                return this.val2Field;
            }
            set {
                this.val2Field = value;
                this.RaisePropertyChanged("Val2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public float Val3 {
            get {
                return this.val3Field;
            }
            set {
                this.val3Field = value;
                this.RaisePropertyChanged("Val3");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.pcservice.com.br/controlpc")]
    public enum Tipo_Medicao {
        
        /// <remarks/>
        TEMPERATURA,
        
        /// <remarks/>
        PESO,
        
        /// <remarks/>
        OXIGENACAO,
        
        /// <remarks/>
        GLICOSE,
        
        /// <remarks/>
        PRESSAO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarLigacaoMCare", WrapperNamespace="http://www.pcservice.com.br/controlpc", IsWrapped=true)]
    public partial class GerarLigacaoMCareRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.pcservice.com.br/controlpc")]
        public BebelBaby.API.wcfGeradorLigacao.PersonalAuthentication PersonalAuthentication;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pcservice.com.br/controlpc", Order=0)]
        public BebelBaby.API.wcfGeradorLigacao.MedicaoMCare medicao;
        
        public GerarLigacaoMCareRequest() {
        }
        
        public GerarLigacaoMCareRequest(BebelBaby.API.wcfGeradorLigacao.PersonalAuthentication PersonalAuthentication, BebelBaby.API.wcfGeradorLigacao.MedicaoMCare medicao) {
            this.PersonalAuthentication = PersonalAuthentication;
            this.medicao = medicao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GerarLigacaoMCareResponse", WrapperNamespace="http://www.pcservice.com.br/controlpc", IsWrapped=true)]
    public partial class GerarLigacaoMCareResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.pcservice.com.br/controlpc", Order=0)]
        public string GerarLigacaoMCareResult;
        
        public GerarLigacaoMCareResponse() {
        }
        
        public GerarLigacaoMCareResponse(string GerarLigacaoMCareResult) {
            this.GerarLigacaoMCareResult = GerarLigacaoMCareResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSControlPCSoapChannel : BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSControlPCSoapClient : System.ServiceModel.ClientBase<BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap>, BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap {
        
        public WSControlPCSoapClient() {
        }
        
        public WSControlPCSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSControlPCSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSControlPCSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSControlPCSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap.GerarLigacaoMCare(BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest request) {
            return base.Channel.GerarLigacaoMCare(request);
        }
        
        public string GerarLigacaoMCare(BebelBaby.API.wcfGeradorLigacao.PersonalAuthentication PersonalAuthentication, BebelBaby.API.wcfGeradorLigacao.MedicaoMCare medicao) {
            BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest inValue = new BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest();
            inValue.PersonalAuthentication = PersonalAuthentication;
            inValue.medicao = medicao;
            BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse retVal = ((BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap)(this)).GerarLigacaoMCare(inValue);
            return retVal.GerarLigacaoMCareResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse> BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap.GerarLigacaoMCareAsync(BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest request) {
            return base.Channel.GerarLigacaoMCareAsync(request);
        }
        
        public System.Threading.Tasks.Task<BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareResponse> GerarLigacaoMCareAsync(BebelBaby.API.wcfGeradorLigacao.PersonalAuthentication PersonalAuthentication, BebelBaby.API.wcfGeradorLigacao.MedicaoMCare medicao) {
            BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest inValue = new BebelBaby.API.wcfGeradorLigacao.GerarLigacaoMCareRequest();
            inValue.PersonalAuthentication = PersonalAuthentication;
            inValue.medicao = medicao;
            return ((BebelBaby.API.wcfGeradorLigacao.WSControlPCSoap)(this)).GerarLigacaoMCareAsync(inValue);
        }
    }
}
